# Site settings
title: Minimal Computing
email: brianlee@ku.edu
description: "Minimal Computing - a working group of GO::DH"
baseurl: "/mincomp"
url: ""
twitter_username: blros
github_username:  blros

# Build settings
markdown: kramdown
permalink: pretty
